### ISSUE TITLE
failed to resolve EastTabs:1.1

### ISSUE THREAD

**Issue by or-dvir** [gilgoldzweig/EasyTabs#4]
hi.
trying to use this library but i get error:
Error:(48, 13) Failed to resolve: tech.goldzweigapps:EasyTabs:1.1

here is my gradle file:
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "24.0.3"
    defaultConfig {
        applicationId "or_dvir.hotmail.com.githubbrowser"
        minSdkVersion 15
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

android.packagingOptions {
    exclude 'META-INF/NOTICE'
    exclude 'META-INF/notice'
    exclude 'META-INF/notice.txt'
    exclude 'META-INF/LICENSE'
    exclude 'META-INF/license'
    exclude 'META-INF/license.txt'

```
exclude 'META-INF/ASL2.0'
exclude 'META-INF/asl2.0'
exclude 'META-INF/asl2.0.txt'
```

}

repositories { maven { url "https://jitpack.io" } }

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    testCompile 'junit:junit:4.12'

```
compile 'com.squareup.picasso:picasso:2.5.2'
compile 'org.codehaus.jackson:jackson-mapper-asl:1.9.13'
compile 'com.octo.android.robospice:robospice:1.4.14'
compile 'com.octo.android.robospice:robospice-spring-android:1.4.14'
compile 'com.android.support:design:25.0.0'
compile 'tech.goldzweigapps:EasyTabs:1.1'
```

}
`

**Comment by gilgoldzweig** [comment]
Issue closed it fixed to a working version
