### ISSUE TITLE
Manifest merger failed : Attribute application@allowBackup value 

### ISSUE THREAD

**Issue by MattGetFlyp** [gilgoldzweig/EasyTabs#5]
I import the library to my app by gradle.
I got this building error :
"Manifest merger failed : Attribute application@allowBackup value=(false)".
I think you should remove allowBackup attribute from your library. (Lib should not have that attribute).

Thank you very much for the great lib.

**Comment by gilgoldzweig** [comment]
That's weird it does not have it and thanks for trying my library try to
add that line in your manifest and anywhy il check it out

**Comment by gilgoldzweig** [comment]
I find the bug and fixed it please use version 1.1.1 instead of 1.1.0 the  readme.md file will be updated soon please tell me if bug resolved
thanks in advance gil goldzweig creator of EasyTabs
